export const login = async(req,res ) => {
    try{


        
    }catch(err){
        console.log(err)
    }
}